services:
  mongodb:
    image: mongo:latest
    container_name: reactrack_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=reactrack

volumes:
  mongo_data: